### ISSUE TITLE
ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead

### ISSUE THREAD

**Issue by Christopher7622** [zyang1580/PDA#10]
I'm using 2.0.3 version pandas
Traceback (most recent call last):
  File "MF/simple_reproduce.py", line 30, in <module>
    from batch_test import *
  File "C:\Users\Administrator\PDAModelTests\MF\batch_test.py", line 10, in <module>
    data = Data2(args)
  File "C:\Users\Administrator\PDAModelTests\MF\load_data.py", line 742, in __init__
    self.load_ori_data(args)
  File "C:\Users\Administrator\PDAModelTests\MF\load_data.py", line 639, in load_ori_data
    user_item_time = train_data.groupby('uid')[('iid','time')].agg(list)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\pandas\core\groupby\generic.py", line 1767, in __getitem__
    raise ValueError(
ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.

**Comment by zyang1580** [comment]
I'd like you to please read ReadMe.md to find the used version of Pandas.
