### ISSUE TITLE
running BPR_top comes across  a bug 

### ISSUE THREAD

**Issue by kkkparty** [zyang1580/PDA#4]
my code  :
python -u MF/train_new_api.py --dataset douban --epoch 10 --save_flag 0 --log_interval 5 --start 0 --end 10 --step 1 --batch_size 2048 --lr 1e-2 --train temp_pop --test temp_pop --saveID temp_pop --cuda 1 --regs 1e-2 --valid_set valid  

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2047] = [2047, 1] does not index into param shape [2048,1]
         [[{{node GatherNd}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MF/train_new_api.py", line 1091, in <module>
    model.Recommender.mf_loss, model.Recommender.reg_loss ])
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2047] = [2047, 1] does not index into param shape [2048,1]
         [[node GatherNd (defined at /workspace/CRD/PDA/MF/model_api.py:346) ]]

Errors may have originated from an input operation.
Input Source operations connected to node GatherNd:
 embedding_lookup_3/Identity (defined at /workspace/CRD/PDA/MF/model_api.py:341)
 concat (defined at /workspace/CRD/PDA/MF/model_api.py:344)

**Comment by zyang1580** [comment]
Are you running the code in the environment satisfying the requirements (seeing readme)? And have you modified some codes? I found that the operations are not the same as this repo regarding the lines reporting bugs.

If the above issues do not exist, could you please check the shape of the input and report the variables related to the lines with bugs?

**Comment by zyang1580** [comment]
Are you running the code in the environment satisfying the requirements (seeing readme)? And have you modified some codes? I found that the operations are not the same as this repo regarding the lines reporting bugs.

If the above issues do not exist, could you please check the shape of the input and report the variables related to the lines with bugs?
